### ISSUE TITLE
How to support pipeline

### ISSUE THREAD

**Issue by penghuiy** [huangmb/jenkins-wechat-notifier#1]
how to support pipeline , like this:
```
post {
    always {
        step([$class: 'WechatNotifier', disablePublish: false, receivers: "xxx", successMsgType: [$class: 'Text', content: "xxx"], failMsgType: [$class: 'Text', content: "xxx"]])
    }
  }
```

**Comment by clair-yang** [comment]
I hava implement SimpleBuildStep,and repackage.now I use
```
step(
        [$class: 'WechatNotifier',
            successMsgType: [$class: 'Text', content: '测试消息，请忽略。构建成功'],
            disablePublish: false,
            receivers: [[type: 'user',id: 'YangPengHui']],
            failMsgType: [$class: 'Text', content: '测试消息，请忽略。构建失败']
        ]
)
```
work well!

**Comment by huangmb** [comment]
我们暂时没使用pipeline，所以也还没考虑pipeline的支持，欢迎提交pr

**Comment by yoyokko** [comment]
@penghuiy  看我的 [PR](https://github.com/huangmb/jenkins-wechat-notifier/pull/6)

**Comment by huangmb** [comment]
> @penghuiy 看我的 [PR](https://github.com/huangmb/jenkins-wechat-notifier/pull/6)

已合并，见https://github.com/huangmb/jenkins-wechat-notifier/releases/tag/2.2.1

**Comment by tomatofrommars** [comment]
试了下 `weworkchatknotify chatIds:'${chatGroupIds}', successMarkdownMsg:'', failMarkdownMsg:''`，可以发送。
