### ISSUE TITLE
需要授权整个公司的组织架构，授权个别运维组出现没有权限

### ISSUE THREAD

**Issue by cypggs** [huangmb/jenkins-wechat-notifier#10]
INFO: 正在新建群聊
Aug 31, 2019 9:00:49 AM com.huangmb.jenkins.wechat.chat.CreateChat doConfigSubmit
INFO: 群名称 jenkins
Aug 31, 2019 9:00:49 AM com.huangmb.jenkins.wechat.chat.CreateChat doConfigSubmit
INFO: 群成员 [case, xxx]
Aug 31, 2019 9:00:49 AM com.huangmb.jenkins.wechat.WeChatAPI createChat
WARNING: {"errcode":60011,"errmsg":"no privilege to access/modify contact/party/agent , hint: [1567242049_37_672ca929031519780941b843b1b71c94], from ip: 119.254.60.51, more info at https://open.work.weixin.qq.com/devtool/query?e=60011"}

**Comment by cypggs** [comment]
顺便感谢下，功能很简单好用，赞一个666

**Comment by huangmb** [comment]
是的，这是企业微信的限制，必须全员可见才有创建群聊的权限。新的企业微信的webhook的机器人功能没有这个限制，你们可以试试这个，用个普通的http请求即可。这个插件可能会增加对机器人的支持，使之有可视化的能力
