### ISSUE TITLE
如何使用这个插件呢?

### ISSUE THREAD

**Issue by windy** [huangmb/jenkins-wechat-notifier#2]
hello 作者好，

感谢提供这个插件，但如何使用呢？要自己打包hpi插件吗?

**Comment by huangmb** [comment]
release里有打包好的hpi

**Comment by windy** [comment]
没有找到 release 目录或分支呀

**Comment by huangmb** [comment]
https://github.com/huangmb/jenkins-wechat-notifier/releases

**Comment by windy** [comment]
好的 我试试

**Comment by windy** [comment]
可以用了，我有空写个使用说明来。

但有个问题，选择发送群聊时，找不到一个群聊（我之前用api创建过的群聊会话也显示不出来)。只能发给部门或个人。

以及有一个建议，在构建操作中，也加上微信通知，因为我想在开始构建时收到一次通知。

**Comment by windy** [comment]
还有一个建议，默认应该设定一个标准的通知内容比较好。

**Comment by hubingliang** [comment]
> 可以用了，我有空写个使用说明来。
> 
> 但有个问题，选择发送群聊时，找不到一个群聊（我之前用api创建过的群聊会话也显示不出来)。只能发给部门或个人。
> 
> 以及有一个建议，在构建操作中，也加上微信通知，因为我想在开始构建时收到一次通知。

我并没有使用成功，期待您的使用说明

**Comment by huangmb** [comment]
> 可以用了，我有空写个使用说明来。
> 
> 但有个问题，选择发送群聊时，找不到一个群聊（我之前用api创建过的群聊会话也显示不出来)。只能发给部门或个人。
> 
> 以及有一个建议，在构建操作中，也加上微信通知，因为我想在开始构建时收到一次通知。
1.  发送群聊需要这个应用是全员可见的，否则没有创建和发送群聊的权限。
2. 这个可以通过[Any Build Step Plugin](http://wiki.jenkins-ci.org/display/JENKINS/Any+Build+Step+Plugin)这个插件来解决的，它可以让构建操作和构建后操作的所有插件共用。

**Comment by huangmb** [comment]
> 还有一个建议，默认应该设定一个标准的通知内容比较好。

这个倒没弄，因为每个场景发送的都是不一样的，没有固定的格式，复制粘贴一下挺快的，或者你可以把模版写在环境变量，引用这个变量。我们一般用Markdown。

**Comment by windy** [comment]
@huangmb 非常感谢你的建议.

这是我整理的一个使用说明: https://yafeilee.me/blogs/98
