### ISSUE TITLE
jenkins 告警的时候出现异常

### ISSUE THREAD

**Issue by xxlaila** [huangmb/jenkins-wechat-notifier#3]
吧告警单独的设置了一个job
jenkins 设置的是job的上下游关联，当上游job构建失败以后触发下游就是告警job，告警job的告警提示都提示为成功。

**Comment by huangmb** [comment]
这个状态是指配置通知的那个Job的状态，对"告警job"这个Job而言确实是成功了。这种情况，也许有两种方案：
1. 通过MultiJob等方式，想办法其中一个任务失败了标记为整个任务失败，在MultiJob上配置上通知。
2.靠什么插件能把下游的告警Job标记为失败。
没有尝试过，建议可以从这两个思路看下有没有解决方案。
有解决方案了欢迎在这里回复下方便大家参考。

**Comment by xxlaila** [comment]
可以不可以获取上一个job构建状态

**Comment by huangmb** [comment]
可以看下这里面有没有上游构建状态的相关变量，或者想办法把构建状态作为参数传递下去
![image](https://user-images.githubusercontent.com/7566936/59559479-91323380-903a-11e9-8e71-dba14b06becc.png)
