### ISSUE TITLE
编辑自定义分组异常

### ISSUE THREAD

**Issue by liangqiangWang** [huangmb/jenkins-wechat-notifier#4]
您好，向您反馈一个bug：
在新建多个自定义分组后，编辑分组时，始终显示的是第一个分组(id=0)的内容。
虽然url变成了"*/wechat/group/2/"，但页面数据仍然是id为0的数据。

**Comment by liangqiangWang** [comment]
好像发现原因了...
`CustomGroupConfig.java`中`getDynamic`函数，写为`groups.get(0)`了，所以只会读取第一个group的数据

**Comment by huangmb** [comment]
方便的话提个pr，避免其他人踩坑。我最近没时间改这个项目
